[package]
name = "almostdefault"
version = "0.2.0"
edition = "2024"
license-file = "LICENSE"
readme = "README.md"

[dependencies]
uiua = { version = "*", default-features = false, features = ["batteries"] }
walkdir = "2"
image = "0"
clap = "4"
clio = { version = "0", features = ["clap-parse"]}
tokio = { version = "1", features = ["full"] }